version: '3'
services:
  logitechmediaserver:
  # --name <name_for_container> \
    image: "davewongillies/squeezebox:latest"
    network_mode: "host"
    ports:
      - 3483:3483
      - 9000:9000
      - 9090:9090
      - 3483:3483/udp
    volumes:
      - ./config:/config
      - ./share:/share/Music
