version: '3'
services:
  logitechmediaserver:
    env_file: .env
    image: "davewongillies/squeezebox:latest"
    network_mode: "${LMS_NETWORK_MODE}"
    ports:
      - 3483:3483
      - 9000:9000
      - 9090:9090
      - 3483:3483/udp
    volumes:
      - "${LMS_CONFIG_DIR}:/config:rw"
      - "${LMS_MUSIC_DIR}:/share/Music:rw"
